spring.application.name=sb-ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=[username]
spring.datasource.password=[password]
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


project.image=images/

spring.app.jwtSecretKey=mySecretKey123912738jeejjwoekknrritntiiwnnfiniropwmdkeoeootnteeootnrsffsskkwieriririnrnwiwirifririririrnf
spring.app.jwtExpirationTokenMs=3000000
spring.application.jwtCookieName=springBootEcom


logging.level.org.springframework=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.iamnana.project=DEBUG