spring.application.name=sb-ecommerce

server.port=${PORT:5000}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


project.image=images/

spring.app.jwtSecretKey=mySecretKey123912738jeejjwoekknrritntiiwnnfiniropwmdkeoeootnteeootnrsffsskkwieriririnrnwiwirifririririrnf
spring.app.jwtExpirationTokenMs=3000000
spring.application.jwtCookieName=springBootEcom


logging.level.org.springframework=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.iamnana.project=DEBUG